package com.modularmods.mcgltf;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertTrue;
import static org.junit.jupiter.api.Assumptions.assumeTrue;

import java.awt.image.BufferedImage;
import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.ArrayList;
import java.util.List;

import javax.imageio.ImageIO;

import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.io.TempDir;

/**
 * Checks that deriving toon data in the mod produces what the offline tool in the
 * Celerant repository produces for the same model.
 *
 * <p>Without this the two derivations would drift, and a model profiled in game would
 * shade differently from the same model profiled on the command line. The example
 * assets committed beside the model are the reference; they are regenerated by the
 * offline tool and are reproducible, so any difference here is the mod's.
 */
class ToonAssetParityTest {
	/**
	 * The two derivations agree on the arithmetic, its precision, and the order it
	 * accumulates in, so most sheets come out identical. What remains is the last bit of
	 * a few transcendental results, which can move a channel by one level on a rounding
	 * boundary. A difference larger than that, or one spread across a sheet, means the
	 * implementations have diverged rather than merely rounded apart.
	 */
	private static final int TOLERANCE = 1;
	private static final double DIVERGENCE = 1.0E-4;
	private static final String PREFIX = "sendagaya-toon";

	@Test
	void derivedAssetsMatchTheOfflineTool(@TempDir Path output) throws Exception {
		Path examples = Path.of(System.getProperty("celerant.examples",
			"../celerant/docs/examples/sendagaya-shino")).toAbsolutePath().normalize();
		Path model = examples.resolve("Sendagaya_Shino.vrm");
		assumeTrue(Files.isRegularFile(model), "Reference example is not available: " + model);

		Path profile = output.resolve("Sendagaya_Shino.vrm.toon.json");
		ToonAssetGenerator.Result result = ToonAssetGenerator.generate(model, output, PREFIX,
			profile);
		assertEquals(17, result.materials());
		assertTrue(result.faceProfiled(), "the example model has a face material to profile");

		assertProfileMatches(examples.resolve(profile.getFileName()), profile);

		List<String> sheets = new ArrayList<>(List.of(PREFIX + "-ramp.png", PREFIX + "-ramp-hair.png",
			PREFIX + "-matcap-metal.png", PREFIX + "-face.png", PREFIX + "-face-shadow.png"));
		for (int index = 0; index < result.materials(); index++) {
			sheets.add(PREFIX + "-light-" + index + ".png");
		}
		List<String> report = new ArrayList<>();
		for (String sheet : sheets) {
			Difference difference = compare(examples.resolve(sheet), output.resolve(sheet));
			if (difference.worst() > TOLERANCE) {
				report.add(sheet + " differs by " + difference.worst() + " levels");
			} else if (difference.channels() > DIVERGENCE * difference.total()) {
				report.add(sheet + " differs on " + difference.channels() + " of "
					+ difference.total() + " channels");
			}
		}
		assertTrue(report.isEmpty(), () -> String.join("\n", report));
	}

	/**
	 * Compares the profiles line by line. Reporting the whole document on a one
	 * character difference buries the difference, so only the differing lines are shown.
	 */
	private static void assertProfileMatches(Path expected, Path actual) throws IOException {
		List<String> left = Files.readAllLines(expected, StandardCharsets.UTF_8);
		List<String> right = Files.readAllLines(actual, StandardCharsets.UTF_8);
		List<String> report = new ArrayList<>();
		for (int line = 0; line < Math.max(left.size(), right.size()) && report.size() < 20; line++) {
			String one = line < left.size() ? left.get(line) : "<missing>";
			String other = line < right.size() ? right.get(line) : "<missing>";
			if (!one.equals(other)) {
				report.add("line " + (line + 1) + ": offline " + one.strip() + " / derived "
					+ other.strip());
			}
		}
		assertTrue(report.isEmpty(), () -> "profile differs\n" + String.join("\n", report));
	}

	/** How far two sheets are apart, and over how much of the sheet. */
	private record Difference(int worst, int channels, int total) {
	}

	private static Difference compare(Path expected, Path actual) throws IOException {
		BufferedImage left = ImageIO.read(expected.toFile());
		BufferedImage right = ImageIO.read(actual.toFile());
		assertEquals(left.getWidth() + "x" + left.getHeight(),
			right.getWidth() + "x" + right.getHeight(), "size of " + actual.getFileName());
		int worst = 0;
		int differing = 0;
		for (int y = 0; y < left.getHeight(); y++) {
			for (int x = 0; x < left.getWidth(); x++) {
				int expectedPixel = left.getRGB(x, y);
				int actualPixel = right.getRGB(x, y);
				for (int shift = 0; shift < 32; shift += 8) {
					int difference = Math.abs(((expectedPixel >> shift) & 255)
						- ((actualPixel >> shift) & 255));
					worst = Math.max(worst, difference);
					differing += difference > 0 ? 1 : 0;
				}
			}
		}
		return new Difference(worst, differing, left.getWidth() * left.getHeight() * 4);
	}
}
