# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx4G
org.gradle.parallel=true
org.gradle.daemon=false

# Project
version=26.2-2.4.0
group=com.modularmods.mcgltf
java_version=25

# Common
minecraft_version=26.2
mod_name=MCglTF
mod_author=TimLee9024, Protoxy
mod_id=mcgltf
license=MIT
credits=JglTF by javagl; Mikk Tangent Generator by jMonkeyEngine
description=A glTF model loader library based on JglTF for Minecraft.
minecraft_version_range=[26.2, 26.3)
neo_form_version=26.2-1

# Fabric
fabric_version=0.156.0+26.2
fabric_loader_version=0.19.3
iris_version=1.11.2+26.2-fabric
sodium_version=0.9.1+mc26.2

# NeoForge
neoforge_version=26.2.0.1-beta
neoforge_loader_version_range=[4,)
